### ISSUE TITLE
Send all button

### ISSUE THREAD

**Issue by tohrxyz** [tohrxyz/zephyrus-wallet#13]
The send screen should contain a `Send all` button, that enters the value of the whole wallet balance into the `amount` input field.  It also need to manage sending balance minus the transaction fee, not the whole balance.

**Comment by tomashrib** [comment]
This can be achieved in this way:

1. Send All button is added somewhere around `amount` input field
2. Transaction confirmation dialog already knows the `totalFee` from pre-built tx , txDetails.fee 
3. Dialog should pass `totalAmount` minus `totalFee` to `broadcastTransaction`
