### ISSUE TITLE
Sync wallet balance upon home screen launch

### ISSUE THREAD

**Issue by tohrxyz** [tohrxyz/zephyrus-wallet#6]
When home screen is launched, the wallet balance should be clicked. Not only after sync button is clicked.

**Comment by tomashrib** [comment]
**Important**
This can't be done, until #5 issue is resolved, which deals with syncing in the background thread, not to freeze the app while doing that.

**Comment by tohrxyz** [comment]
This is solved in commit ``50efbe9a5e718ea31867be7f8197956297b63253``

Closing issue.
